[package]

name = "mandelrust"
version = "0.1.0"
authors = [ "gavinb@antonym.org" ]

build = "build.rs"

[[bin]]

name = "mandelrust"

[dependencies]

gl = "0.0.12"
glfw = "0.0.8"
gl_common = "0.0.4"
khronos_api = "0.0.5"

[build-dependencies]

gl_generator = "*"
khronos_api = "0.0.5"
